default-remote: local
remotes:
  IncusOS:
    addr: https://10.0.10.64:8443
    auth_type: tls
    project: default
    protocol: incus
    public: false
  images:
    addr: https://images.linuxcontainers.org
    protocol: simplestreams
    public: true
  local:
    addr: unix://
    protocol: incus
    public: false
aliases: {}
defaults:
  list_format: ""
  console_type: ""
  console_spice_command: ""
