apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cilium
  pass_credentials_all: false
  password: ""
  url: https://helm.cilium.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: democratic-csi
  pass_credentials_all: false
  password: ""
  url: https://democratic-csi.github.io/charts/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: renovate
  pass_credentials_all: false
  password: ""
  url: https://docs.renovatebot.com/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: rancher
  pass_credentials_all: false
  password: ""
  url: https://releases.rancher.com/server-charts/latest
  username: ""
